CREATE TABLE `clients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(20),
	`name` varchar(255) NOT NULL,
	`nif` varchar(20),
	`type` enum('singular','colectivo','estrangeiro') DEFAULT 'colectivo',
	`address` text,
	`city` varchar(100),
	`province` varchar(100),
	`country` varchar(100) DEFAULT 'Angola',
	`phone` varchar(30),
	`email` varchar(320),
	`contactPerson` varchar(255),
	`paymentTerms` int DEFAULT 30,
	`creditLimit` decimal(15,2),
	`notes` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `clients_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `company` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`nif` varchar(20) NOT NULL,
	`address` text,
	`city` varchar(100),
	`province` varchar(100),
	`country` varchar(100) DEFAULT 'Angola',
	`phone` varchar(30),
	`email` varchar(320),
	`website` varchar(255),
	`logoUrl` text,
	`taxRegime` enum('geral','simplificado','exclusao') DEFAULT 'geral',
	`vatNumber` varchar(20),
	`bankName` varchar(100),
	`bankIban` varchar(50),
	`bankSwift` varchar(20),
	`digitalSignatureKey` text,
	`agtPortalUser` varchar(100),
	`agtPortalPassword` text,
	`softwareValidationNumber` varchar(50) DEFAULT '000/AGT/202X',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `company_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `inventory_movements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`productId` int NOT NULL,
	`type` enum('entrada','saida','ajuste','transferencia') NOT NULL,
	`quantity` decimal(10,4) NOT NULL,
	`unitCost` decimal(15,4),
	`totalCost` decimal(15,2),
	`reference` varchar(100),
	`invoiceId` int,
	`supplierId` int,
	`notes` text,
	`movementDate` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `inventory_movements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invoice_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoiceId` int NOT NULL,
	`lineNumber` int NOT NULL,
	`productId` int,
	`productCode` varchar(50),
	`description` varchar(500) NOT NULL,
	`unit` varchar(20) DEFAULT 'UN',
	`quantity` decimal(10,4) NOT NULL,
	`unitPrice` decimal(15,4) NOT NULL,
	`discountPercent` decimal(5,2) DEFAULT '0',
	`discountAmount` decimal(15,2) DEFAULT '0',
	`vatRate` decimal(5,2) NOT NULL,
	`vatExemptReason` varchar(255),
	`vatAmount` decimal(15,2) NOT NULL,
	`subtotal` decimal(15,2) NOT NULL,
	`total` decimal(15,2) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `invoice_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invoice_series` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(20) NOT NULL,
	`name` varchar(100) NOT NULL,
	`documentType` enum('FT','FR','FS','FA','NC','ND','RC','RG') NOT NULL,
	`validationCode` varchar(50),
	`lastNumber` int NOT NULL DEFAULT 0,
	`year` int NOT NULL,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoice_series_id` PRIMARY KEY(`id`),
	CONSTRAINT `invoice_series_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`seriesId` int NOT NULL,
	`documentType` enum('FT','FR','FS','FA','NC','ND','RC','RG') NOT NULL,
	`number` int NOT NULL,
	`fullNumber` varchar(50) NOT NULL,
	`atcud` varchar(100),
	`hash` varchar(512),
	`hashControl` varchar(4),
	`clientId` int,
	`clientName` varchar(255),
	`clientNif` varchar(20),
	`clientAddress` text,
	`issueDate` datetime NOT NULL,
	`dueDate` datetime,
	`operationDate` datetime,
	`subtotal` decimal(15,2) NOT NULL,
	`vatAmount` decimal(15,2) NOT NULL,
	`discountAmount` decimal(15,2) DEFAULT '0',
	`withholdingTaxAmount` decimal(15,2) DEFAULT '0',
	`totalAmount` decimal(15,2) NOT NULL,
	`currency` varchar(3) DEFAULT 'AOA',
	`exchangeRate` decimal(10,4) DEFAULT '1.0000',
	`deliveryLocation` text,
	`deliveryDate` datetime,
	`status` enum('rascunho','emitida','paga','parcialmente_paga','anulada','vencida') NOT NULL DEFAULT 'rascunho',
	`relatedInvoiceId` int,
	`relatedInvoiceNumber` varchar(50),
	`paymentMethod` enum('numerario','transferencia','cheque','cartao','outro'),
	`paymentDate` datetime,
	`paidAmount` decimal(15,2) DEFAULT '0',
	`notes` text,
	`internalNotes` text,
	`pdfUrl` text,
	`xmlUrl` text,
	`agtSubmitted` boolean DEFAULT false,
	`agtSubmissionDate` datetime,
	`agtResponse` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`),
	CONSTRAINT `invoices_fullNumber_unique` UNIQUE(`fullNumber`)
);
--> statement-breakpoint
CREATE TABLE `product_categories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`description` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `product_categories_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(50) NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`categoryId` int,
	`type` enum('produto','servico') NOT NULL DEFAULT 'produto',
	`unit` varchar(20) DEFAULT 'UN',
	`price` decimal(15,2) NOT NULL,
	`costPrice` decimal(15,2),
	`vatRate` decimal(5,2) NOT NULL DEFAULT '14.00',
	`vatExemptReason` varchar(255),
	`isVatExempt` boolean NOT NULL DEFAULT false,
	`stockControl` boolean NOT NULL DEFAULT true,
	`minStock` decimal(10,2) DEFAULT '0',
	`currentStock` decimal(10,2) DEFAULT '0',
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `products_id` PRIMARY KEY(`id`),
	CONSTRAINT `products_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `suppliers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(20),
	`name` varchar(255) NOT NULL,
	`nif` varchar(20),
	`type` enum('singular','colectivo','estrangeiro') DEFAULT 'colectivo',
	`address` text,
	`city` varchar(100),
	`province` varchar(100),
	`country` varchar(100) DEFAULT 'Angola',
	`phone` varchar(30),
	`email` varchar(320),
	`contactPerson` varchar(255),
	`paymentTerms` int DEFAULT 30,
	`notes` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `suppliers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`passwordHash` varchar(255),
	`loginMethod` varchar(64),
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);
